argo/apps/Chart.yaml, argo/apps/templates/mongodb.yaml, argo/apps/templates/namespace-init.yaml, argo/apps/templates/securebaking-spring-config-server.yaml, argo/apps/templates/securebanking-rcs.yaml, argo/apps/templates/securebanking-rs.yaml, argo/apps/values.yaml
Add Argo application definitions.
Preconfigured to apply the applications to the argo kubernetes context under the namespace `dev`.
=> Argo application definitions

argo/apps/templates/mongodb.yaml, argo/apps/templates/namespace-init.yaml, argo/apps/templates/securebaking-spring-config-server.yaml, argo/apps/templates/securebanking-rcs.yaml, argo/apps/templates/securebanking-rs.yaml, argo/apps/values.yaml
Helm will decide the namespace to deploy.
default the sync policy to manual. Workflows will trigger a sync.
=> remove the namespace meta

argo/workflows/environment-creation.yaml, argo/workflows/slack-build.yaml, argo/workflows/slack-rebuild-notify.yaml
Add webhook workflows that will allow for the creation of an environment. This can be used via slack and github.
=> webhook workflows

README.md, argo/apps/README.md, cluster-setup/namespace-setup/README.md
Add Readme to describe the purpose of an argo Application definintion and extra definitions for the helm parameters of our namespace initialisation chart.
issue: https://github.com/SecureBankingAccessToolkit/sbat-cd/issues/11
=> add readmes

argo/workflows/environment-creation.yaml
The uis deploy in parallel with rs and rcs.
issue: https://github.com/SecureBankingAccessToolkit/securebanking-ui/issues/13
=> add secure banking ui to the env creation pipeline

argo/workflows/git-build.yaml
Implement a workflow that deploys an application based on the specific github pull request event.
=> git workflow for deploying pr containers

argo/parent-app/Chart.yaml, argo/parent-app/README.md, argo/parent-app/templates/applications.yaml, argo/parent-app/templates/namespace-init.yaml, argo/parent-app/values.yaml
Create a parent application that will allow the controlled destruction of child apps without having to use helm to install or upgrade them
=> create a parent app

argo/apps/values.yaml, argo/parent-app/templates/namespace-init.yaml
Add self healing and auto pruning redundant resources to the automated sync policy.
=> allow resources to self heal

argo/workflows/slack-rebuild-notify.yaml
escape slack quotes as the pipeline is trying to execute the embedded command.
=> escape quotes for environment build

argo/apps/templates/ig.yaml
Create IG application manifest for easy deployment and limit dependency on skaffold
issue: https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-demo/issues/38
=> add ig application to environment setup

argo/apps/templates/ig.yaml, argo/parent-app/templates/applications.yaml
IG kustomize overlay path should be supplied by the destination namespace.
=> Developer environments

argo/apps/templates/namespace-init.yaml, argo/parent-app/templates/applications.yaml
forceString parameter must be set to true for the boolean values.
related PR: https://github.com/SecureBankingAccessToolkit/sbat-cd/pull/41
=> force string value

argo/workflows/slack-rebuild-notify.yaml
Make the slack message more space efficient and have it post actual https links
=> modify message so it doesnt take up so much space

argo/workflows/git-build.yaml
Fix the git build workflow as the argo sync and wait workflow was renamed recently but the git build wasnt updated to reflect this.
=> fix workflow template

argo/apps/templates/ig.yaml, argo/apps/templates/mongodb.yaml, argo/parent-app/templates/applications.yaml
Add sync waves to application to specify order of deployment.
This will allow us to add functional tests without having to go through a workflow pipeline
Add resource finalisers for clean delete
issue: https://github.com/SecureBankingAccessToolkit/sbat-cd/issues/7
=> add syncwaves to all apps

argo/apps/templates/namespace-init.yaml, argo/apps/values.yaml, cluster/certificate/templates/wildcard-secret.yaml, cluster/certificate/values.yaml
Default wildcard certificate config is no longer required.
=> remove redundant config

argo/apps/templates/ig.yaml, argo/apps/values.yaml
allows ig tag and branch to be changed
issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/89
=> allow changing ig container branch and tag

argo/apps/templates/ig.yaml
- change the image on the application defition for IG
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/211
=> 211: argo Pr sync IG application

argo/apps/templates/iam-init.yaml
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/224
=> 224: Create PSU in pipeline

argo/apps/templates/iam-init.yaml
Reverts SecureBankingAccessToolkit/sbat-cd#59
=> Revert "224: Create PSU in pipeline"

argo/apps/templates/iam-init.yaml, argo/apps/templates/securebanking-rcs.yaml, argo/apps/templates/securebanking-ui.yaml, argo/apps/values.yaml, cluster/certificate/README.md
- Updated github actions with gcloud environment configuration fix version
- Deleted template values unused
- Updated the template application to use the env properties from `platform-config` configMap
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/229
=> 229: cdk-cdm-fidc same configuration

argo/apps/templates/sbat-iam-init.yaml, argo/apps/templates/sbat-test-user-init.yaml, argo/apps/values.yaml
https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/276
=> 276: Fixing values to use camelCase as per helm best practices

argo/apps/templates/sbat-iam-init.yaml, argo/apps/templates/sbat-test-user-init.yaml
https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/276
=> 276: Removing trailing '/' from imageOverride.repo

argo/apps/templates/sbat-iam-init.yaml, argo/apps/values.yaml
No point in fighting the helm value syntax. Follow the guide (thanks Dan); https://helm.sh/docs/chart_best_practices/values/
=> 276: Fix failing initialize-sbat-namespaces pipeline again

argo/apps/templates/securebanking-ui.yaml
https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/799
=> 799: Removing helm params of securebanking-ui used by Swagger deployment only

argo/apps/templates/ig.yaml
Change the folder location for where ARGO picks up the files
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/860 & https://github.com/SecureApiGateway/SecureApiGateway/issues/854
=> 854 - Create Kustomize Overlays from ForgeOps k8s manifests for deployment of IG

argo/apps/templates/securebanking-rs.yaml
Adding Spring testdata configuration of test user accountIds to RS deployment.
https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/888
=> 888: Adding springConfig overrides for RS

argo/apps/templates/securebanking-rs.yaml
- Disabling all versions except 3.1.8, 3.1.9 and 3.1.10
https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/886
=> 886: RS Discovery configuration

argo/apps/templates/sbat-test-user-init.yaml, argo/apps/values.yaml
Add in variable override for test initialiser 
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/906
=> 906 Add in yaml manifest for running test initialiser as a job

argo/apps/templates/fidc-configurator.yaml, argo/apps/templates/remote-consent-server.yaml, argo/apps/templates/remote-consent-ui.yaml, argo/apps/templates/test-facility-bank.yaml, argo/apps/templates/test-user-account-creator.yaml
Issue: https://github.com/secureapigateway/secureapigateway/issues/851
=> 851: Rename argo applications to reflect deployed names

argo/apps/templates/fidc-configurator.yaml, argo/apps/templates/remote-consent-server.yaml, argo/apps/templates/remote-consent-ui.yaml, argo/apps/templates/test-facility-bank.yaml, argo/apps/templates/test-user-account-creator.yaml, argo/apps/values.yaml
Use new values format and add in the repo override for argo
Change remoteConsentUI to full name
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/939
=> 939 Standardise helm charts

argo/apps/templates/remote-consent-server.yaml
https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/1010
=> 1010: Configure RCS to connect to MongoDB

argo/apps/templates/ig.yaml, argo/apps/values.yaml
Change repo URLs to new location
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/987
=> 987: Artifact Registry Migration

argo/apps/templates/fidc-configurator.yaml
Remove cronjob from value names
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1282
=> 1282: Stop FIDC running as cronjob

argo/apps/core/Chart.yaml, argo/apps/core/README.md, argo/apps/core/templates/fidc-configurator.yaml, argo/apps/core/templates/ig.yaml, argo/apps/core/templates/namespace-init.yaml, argo/apps/core/templates/sbat-iam-secret-manager.yaml, argo/apps/core/templates/test-user-account-creator.yaml, argo/apps/core/values.yaml
Create Child templates for dev-core
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1304
=> 1304: Create dev deployment of SAPI-G core

argo/apps/core/values.yaml
Set test user create as job as only object being created
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1315
=> 1315: Remove unwanted config from dev-core

cluster/certificate/values.yaml
Change cloudType to be CDK initially
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1363
=> 1368: Fix Check Env Exists curl commands in deployment workflows

argo/apps/core/templates/namespace-init.yaml, argo/apps/ob/templates/namespace-init.yaml
Add in cloudtype as a parameter so that the if statement for cloud service account will work
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1374
=> 1374: Fix namespace init argocd template

argo/apps/core/templates/test-trusted-directory.yaml, argo/apps/core/values.yaml
Add in argo template for creating new test trusted directory deployment in core
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1342
=> 1342: Create k8s deployment for Test Trusted Directory

argo/apps/core/templates/ig.yaml, argo/apps/core/templates/namespace-init.yaml, argo/apps/core/templates/test-trusted-directory.yaml, argo/apps/core/values.yaml, argo/apps/ob/templates/ig.yaml, argo/apps/ob/templates/namespace-init.yaml, argo/apps/ob/values.yaml, cluster/certificate/templates/mtls-cert-secret.yaml, cluster/certificate/templates/sapig-cert-secret.yaml, cluster/certificate/templates/ttd-cert-secret.yaml, cluster/certificate/values.yaml
Removing need for 7.3.0 in kustomize directory 
New secrets for supporting different TLS certs for ingresses
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1511
=> 1511: Improvements from POC

argo/apps/core/templates/ig.yaml, argo/apps/core/templates/namespace-init.yaml, argo/apps/core/templates/test-trusted-directory.yaml, argo/apps/core/values.yaml, argo/apps/ob/templates/ig.yaml, argo/apps/ob/templates/namespace-init.yaml, argo/apps/ob/values.yaml, cluster/certificate/templates/mtls-cert-secret.yaml, cluster/certificate/templates/sapig-cert-secret.yaml, cluster/certificate/templates/ttd-cert-secret.yaml, cluster/certificate/values.yaml
Update OB-V4 branch for latest changes from master
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1511
=> 1511: Improvements from POC (#138)

argo/apps/core/templates/namespace-init.yaml, argo/apps/ob/templates/namespace-init.yaml
Incorrect value being used for service account ID
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1533
=> 1533: Create cloud config for am-fahrenheit & use nightly-core env to test

argo/apps/ob/templates/test-facility-bank.yaml
Add in 4.0.0: true to rs discovery
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1602
=> 1602: Build and Deploy SAPIG 4.0.0

argo/apps/core/values.yaml, argo/apps/ob/values.yaml, cluster/certificate/values.yaml
Update secret names for private keys
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1590
=> 1590: Rename environment

argo/apps/ob/templates/test-trusted-directory.yaml, argo/apps/ob/values.yaml
Add TTD to OB Envs
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1624
=> 1642: Deploy TTD to Devenvs OB

argo/apps/ob/templates/test-user-account-creator.yaml
Override cronjob value for OB test user
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1676
=> 1676: Split IG into AS/RS and deploy to Devenvs

argo/apps/core/templates/namespace-init.yaml, argo/apps/core/values.yaml, argo/apps/ob/values.yaml
Revert any branch or tags for testing
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1679
=> 1679: Migrate IG Components to Helm
