SecureApiGateway/sbat-cd

- argo/workflows/functional-test.yaml
Create a workflow template for the functional tests.
It will pickup the domain from a configMap, that is generated when the environment is created.
> create workflow template for functional tests

- argo/workflows/morning-dev-sync.yaml
Sync the dev environment every morning at 8am.
This calls the `create-environment` pipeline that forces argo to sync the secure banking applications only.
> sync dev every morning

- cluster-setup/namespace-setup/templates/wildcard-secret.yaml
- cluster-setup/namespace-setup/values.yaml
Add optional wildcard when a namespace is created. This will bring it down from the secrets manager and prevent cert manager for breaking out environment.
> optional wildcard cert with namespace setup

- argo/apps/templates/namespace-init.yaml
- argo/apps/templates/securebanking-rcs.yaml
- argo/apps/templates/securebanking-rs.yaml
- argo/apps/values.yaml
Let our argo pipelines define its own config overrides for obfuscated config. both the domain name of the developer environment and the the GCP project name that stores the external certificates.
https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-rs/issues/40
> add parameter configuration for pipelines

- argo/apps/templates/mongodb.yaml
- argo/apps/templates/namespace-init.yaml
- argo/apps/templates/securebaking-spring-config-server.yaml
- argo/apps/templates/securebanking-rcs.yaml
- argo/apps/templates/securebanking-rs.yaml
- argo/workflows/environment-creation.yaml
- argo/workflows/sync-and-wait.yaml
The argo applications are created each morning via helm. Add a suffix for the namespace they will be created in and supply an additional step in the environment creation that will let you destroy your namespace before creating an environment.
This allows for the quick teardown and rebuild of an enviornment.
> namespace apps and all destroying of namesapces in workflows

- argo/workflows/sync-and-wait.yaml
- argo/workflows/sync-application.yaml
Allow synchronising of individual applications. This will allow us to deploy applications to kubernetes in the PR phase of a git request while letting us set different docker tags for our apps.
> add sync application pipeline

- argo/workflows/morning-dev-sync.yaml
Set the morning build to trigger half hour later. its currently set to trigger before argo is even created in the morning.
we have to set it to 8:30 as BST is 1 hour ahead of UTC. this will actually trigger at 7:30am.
> start morning build at 8:30

- argo/apps/templates/namespace-init.yaml
- argo/apps/values.yaml
init-charts repo has been renamed to sbat-cd, some of the config must change to reflect this.
issue: https://github.com/SecureBankingAccessToolkit/sbat-cd/issues/16
> rename from init-charts to sbat-cd

- argo/apps/templates/securebanking-ui.yaml
Add the Application manifest for argo to monitor and deploy the securebanking-ui into the `dev` cluster/namespace.
issue: https://github.com/SecureBankingAccessToolkit/sbat-cd/issues/17
> add the securebanking argo application manifest

- argo/apps/templates/mongodb.yaml
- argo/apps/values.yaml
authentication is not required for local development/ dev cluster.
it has been disabled via argo.
> disable auth by default for the dev namespace

- argo/workflows/sync-and-wait.yaml
- argo/workflows/sync-application.yaml
Add `branch` configuration to the sync workflows.
This will allows us to synchronise applications on specific branches during the PR phase allowing us to perform functional/deployment tests before merge.
> synchronize applications with branch

- argo/apps/templates/mongodb.yaml
- argo/apps/templates/securebanking-rcs.yaml
- argo/apps/templates/securebanking-rs.yaml
- argo/apps/templates/securebanking-ui.yaml
- argo/apps/values.yaml
- argo/parent-app/templates/applications.yaml
- argo/parent-app/values.yaml
Apply image tags to the child apps so we can easily set test containers.
Apply the presync hook to the mongodb so the resources can remain if the argo application is destroyed.
change `config.domain` to `ingress.domain`
Apply mongodb host based on the helm chart release name.
> Apply new config for dev envs

- argo/apps/templates/mongodb.yaml
- argo/apps/templates/namespace-init.yaml
- argo/apps/templates/securebaking-spring-config-server.yaml
- argo/apps/templates/securebanking-rcs.yaml
- argo/apps/templates/securebanking-rs.yaml
- argo/apps/templates/securebanking-ui.yaml
- argo/apps/values.yaml
Move the namespace setup to the parent app and ensure that it is self healing, this way the namespace and services will always repair themselves. A fresh environment can be created by simply deleting the namespace and waiting for the repair.
> move namespace to apps

- argo/workflows/environment-creation.yaml
- argo/workflows/slack-rebuild-notify.yaml
Init namespace is no longer required in the workflow. this is done automatically by the parent app.
give more slack information on an environment when it has been built.
> remove init namesapce from the workflow

- cluster-setup/namespace-setup/README.md
- cluster-setup/namespace-setup/templates/wildcard-secret.yaml
- cluster-setup/namespace-setup/values.yaml
Allows us to select a certificate based on the namespace we are deploying into. Defaults to the basic wildcard.
Cert selected by the namespace that the chart deploys into.
Remove unneeded config.
> different certs based on namesapce

- argo/apps/templates/namespace-init.yaml
- argo/apps/values.yaml
- argo/parent-app/templates/applications.yaml
- argo/parent-app/values.yaml
add parameter to set the default wildcard certificate for the argo applications.
> add parameter to set the defaultWildcard in argo

- argo/parent-app/README.md
Add a bit to the readme to explain and redirect to the argo app of apps pattern that we are using for single click environments.
> documentation for the app of apps parrent

- argo/apps/templates/functional-tests.yaml
Add functional test resource on a high sync-wave to ensure that it will execute after the services are healthy
issue: https://github.com/SecureBankingAccessToolkit/sbat-cd/issues/7
> add functional test application

- cluster/certificate/templates/cert-secret.yaml
- cluster/certificate/values.yaml
the default wildcard is needed as some namespaces share the `dev` wildcard.
cleanup from: https://github.com/SecureBankingAccessToolkit/sbat-cd/pull/53
> Add default wildcard

- cluster/certificate/README.md
- cluster/certificate/templates/cert-secret.yaml
- cluster/certificate/values.yaml
This chart used to always use the namespace as a prefix when trying to
obtain the correct cert from Google Secret Manager. e.g. when installing
CDK to bohocode-cdk namespace, this chart tried to pull the secret called
bohocode-cdk-crt and bohocode-cdk-key from google secret mangager.
However, the cert-renewal pipeline creates certs based on the sbat
namespace, e.g. bohocode, not the cdk namespace, e.g. bohcode-cdk. So
the pipeline would fail to find the bohocode-cdk-crt and key secrets and
the ingress would fall back to the default kubernetes cert.
The new variable externalCert.certPrefix can be used to set the cert
prefix using this chart, e.g.
```
helm upgrade cdk cluster/certificate --install --namespace bohocode-cdk --create-namespace \
--set externalCert.projectId=$PROJECT_ID --set …
```
> 294: Create a new variable that controls the cert sub-domain

- argo/apps/templates/mongodb.yaml
Bump up mongodb version to 12.1.15 as the old version is no longer found on bitnami. As a result the rs service is unable to start.
> Bump up mongodb version to 12.1.15 

- argo/apps/templates/ig.yaml
- Updated ig helm template kustomize path to use the new one pointed to 7.1.0/securebanking
Issue: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/523
> 523: Update ig version references

- argo/apps/templates/sbat-iam-init.yaml
- argo/apps/templates/sbat-test-user-init.yaml
- argo/apps/values.yaml
Add two new charts to argocd config that will deploy;
- The `securebanking-openbanking-uk-fidc-initializer` which will
initialize the FR Platform
- The `securebanking-openbanking-test-data-initializer` which will
create test users and data in the platform/sbat instance such that the
functional tests will be able to be run.
Issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/276
> 276: Deploy initializers into sbat namespaces using argocd

- argo/apps/templates/sbat-iam-init.yaml
- argo/apps/templates/sbat-test-user-init.yaml
https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/276
> 276: Fxing helm parameters passed by argo to be strings (this is the only type supported)

- argo/apps/templates/sbat-iam-init.yaml
I was using the wrong service name in the argocd template for the iam-initialiser
> 276: Make PR push to argo deployment work correctly

- argo/apps/templates/sbat-iam-init.yaml
'-' is not a valid character when passing args to argo
> 276: Fix broken initialise-sbat-namespaces pipeline

- argo/apps/templates/sbat-iam-init.yaml
- argo/apps/values.yaml
The values expected by the argocd chart didn't accept what we were passing. Stars not alligned...
> 276: Fix failing initialize-sbat-namespaces pipeline

- argo/apps/templates/sbat-iam-init.yaml
Argo app names must all be lower case or -
> 276: Fix failing initialize-sbat-namespaces

- argo/apps/templates/sbat-iam-init-config.yaml
- argo/apps/templates/sbat-iam-secret-manager.yaml
- argo/apps/values.yaml
Have the secret created in the new [dev repo](https://github.com/SecureApiGateway/sapig-openbanking-uk-developer-envs)
Create new argo template for creating the IAM initialiser config
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/702
> 702 - Split the external secret manager deployment out of iam

- argo/apps/templates/mongodb.yaml
Up the chart version for mongodb as the previous is no longer 'available' newer version tested and seems to be okay
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/725
> 725-Fix mongodb not starting up

- .github/workflows/slackNotification.yml
New github action workflow which will trigger when there is a push to master, push to master is only possible when a PR is complete so does the same result as a merge being closed
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/720
> 720 - Slack notification when PR complete 

- cluster/certificate/templates/ig-ob-signing-key-secret.yaml
- cluster/certificate/templates/ig-test-trusted-directory-secret.yaml
- cluster/certificate/values.yaml
ig-ob-signing-key-secret.yaml represents the JWT signing key to sign Open Banking API response messages (OBSeal)
ig-test-trusted-directory-secret.yaml contains secrets required for IG to run a Test Trusted Directory. The CA secret is the signing key used to sign the certificates issued by the authority. The signingKey secret is used to sign the SSA JWTs issued by the directory.
https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/764
> 764: Adding secrets for the Open Banking Signing Key and Test Trusted Directory Keys

- cluster/certificate/templates/ig-test-trusted-directory-secret.yaml
- cluster/certificate/values.yaml
New Google Secret: `test-trusted-dir-keystore` contains both the ca private key and the jwt-signing private key.
Managing one store & secret simplifies the process of setting up the Test Trusted Directory.
https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/764
> 764: Combining test trusted directory ca and signing key secrets into a single keystore

- cluster/certificate/templates/ig-truststore-secret.yaml
Wrong way around for file names
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/766
> Correct filenames for secret

- argo/apps/templates/fidc-configurator.yaml
- argo/apps/templates/remote-consent-server.yaml
- argo/apps/templates/remote-consent-ui.yaml
- argo/apps/templates/test-facility-bank.yaml
- argo/apps/templates/test-user-account-creator.yaml
- argo/apps/values.yaml
The values being set in argocd parameters are not matching those used by the argo application templates.
Everything needs to match up again!
Issue: https://github.com/secureapigateway/secureapigateway/issues/934
> 934: Rename the apps in the values file for argo apps

- argo/apps/templates/fidc-configurator.yaml
- argo/apps/templates/remote-consent-server.yaml
- argo/apps/templates/remote-consent-ui.yaml
- argo/apps/templates/test-facility-bank.yaml
- argo/apps/templates/test-user-account-creator.yaml
- argo/apps/values.yaml
Using - in value names causes parse issues in YAML 
Revert to using camel case for the values
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/934
> 934: Use camelcase for values as '-' causes errors in yaml

- argo/apps/templates/test-facility-bank.yaml
To be able disabled or enabled to support push customer info account data has been added new spring properties
- Added spring properties to enabled or disabled support to push customer info account data using DataApi
- Enabled by default for devs environments
This property is false by default when rs.data.customerInfo.enabled property isn't provided in the configuration or environment variable. Not needs to be set in relenvs environments, in relenvs environments must be always disabled.
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1070
> 1070: customer info account data spring config

- argo/apps/templates/test-facility-bank.yaml
- deleted disabled funds confirmation APIS from test facility bank to be added in RS discovery
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/601
> 601 added funds confirmation API to discovery endpoint

- argo/apps/templates/fidc-configurator.yaml
- argo/apps/values.yaml
Add in new env variable for toggling the fidc configurator to be installed or not, by default it is true and for nightly we are setting it to false during the pipeline
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/901
> 901 Disable initializer for nightly env

- argo/apps/core/templates/namespace-init.yaml
- argo/apps/ob/templates/namespace-init.yaml
- cluster/certificate/templates/ob-cert-secret.yaml
- cluster/certificate/values.yaml
Don't want OB secrets being created for Core, will use value of env.sapigType for wherever to create or not
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1315
> 1315: Remove unwanted config from dev-core

- argo/apps/core/templates/sbat-iam-secret-manager.yaml
- argo/apps/core/templates/test-user-account-creator.yaml
- argo/apps/ob/templates/remote-consent-server.yaml
- argo/apps/ob/templates/remote-consent-ui.yaml
- argo/apps/ob/templates/sbat-iam-secret-manager.yaml
- argo/apps/ob/templates/test-facility-bank.yaml
- argo/apps/ob/templates/test-user-account-creator.yaml
- The test initialiser seems to rely on the CDK / Cloud instance being created and configured, so have this component created after IG & FIDC Initialiser has ran (they rely on each other) 
- Set sbat-iam-secret-manager to 1 as it doesn't reply on anything else either
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1362
> 1362: Try improve sync timings of components being created in ArgoCD

- argo/apps/ob/templates/test-user-account-creator.yaml
Remove override of sapigType as being set by configmap
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1459
> 1459: Cleanup use of sapigType in test init

- argo/apps/core/templates/namespace-init.yaml
- argo/apps/core/values.yaml
- argo/apps/ob/templates/namespace-init.yaml
- argo/apps/ob/values.yaml
- cluster/certificate/templates/cloud-service-account.yaml
- cluster/certificate/values.yaml
Add in new cloud service account env vars, by default the nightly-private-key|id was being used, seeing as this is a new tenant the service account doesnt exist. Need a way of using a different secret for the test Core deployment
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1533
> 1533: Create cloud config for am-fahrenheit & use nightly-core env to test

- argo/apps/core/templates/ig.yaml
- argo/apps/core/templates/namespace-init.yaml
- argo/apps/core/templates/test-trusted-directory.yaml
- argo/apps/core/values.yaml
- argo/apps/ob/templates/namespace-init.yaml
- argo/apps/ob/templates/test-trusted-directory.yaml
- argo/apps/ob/values.yaml
- Need to amend previous ig template to only deploy core|ob
- New template to deploy the TTD
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1670
> 1670: Move Kustomize base templates to individual repos

- argo/apps/core/values.yaml
- cluster/certificate/templates/mtls-cert-secret.yaml
Use existing mtls cert for TTD for the time being
Issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1676
> 1676: Split IG into AS/RS and deploy to Devenvs

- argo/apps/core/templates/fapi-pep-as.yaml
- argo/apps/core/values.yaml
Allow the signing kid to be overwritten for fapi-pep-as
Issue: https://pingidentity.atlassian.net/browse/OPENIG-9515
> OpenIG-9515: FAPI Conformance Suite (Tests)
